/*********************************************************************/
/*STD    CLPBASEBND                                                  */
/*EXI    TEXT('Midas DMLIB RE files Reorganisation')                 */
/*********************************************************************/
/*                                                                   */
/*       Midas - General Ledger Module                               */
/*                                                                   */
/*       REC000800 - RE DMLIB Files Reorganisation                   */
/*                                                                   */
/*       (c) Misys International Banking Systems Ltd. 2015           */
/*                                                                   */
/*       Last Amend No. MD030124 *Create   Date 18Jun15              */
/*                                                                   */
/*********************************************************************/
/*                                                                   */
/*       MD030124 - RECOMD has never been reorganized. Introduce     */
/*                  new component to organize RE file in COB.        */
/*                                                                   */
/*********************************************************************/
             PGM
 
             DCL        VAR(&MEM) TYPE(*CHAR) LEN(70)
 
             COPYRIGHT TEXT('(c) Misys International Banking Systems Ltd. +
                          2015')
 
/* Global monitor message */
 
             MONMSG     MSGID(CPF0000 MCH0000 RPG0000) EXEC(GOTO +
                          CMDLBL(ABNOR))
 
             CHGJOB     SWS(00000000)
 
             SNDPGMMSG  MSG('REC000800 - RE DMLIB Files Reorganisation') +
                          TOMSGQ(MRUNQ)
 
/* Reorganise files */
 
             CALL       PGM(SCC000060) PARM('RECOMD' '*FIRST')
             IF         COND(%SWITCH(XXXXXX11)) THEN(GOTO +
                          CMDLBL(ABNOR))
 
 
             GOTO       CMDLBL(ENDPGM)
 
/* Abnormal ending: */
 
ABNOR:
             CHGJOB     SWS(XXXXXX11)
 
/* Report an error */
 
             CHGVAR     VAR(&MEM) VALUE('REC000800 - RE DMLIB Files Reor+
                          ganisation FAILED')
             MONMSG     MSGID(CPF0000 MCH0000 RPG0000)
 
             SNDPGMMSG  MSGID(MEM5052) MSGF(MIDAS) MSGDTA(&MEM) +
                          TOMSGQ(MOPERQ MRUNQ)
             MONMSG     MSGID(CPF0000 MCH0000 RPG0000)
 
ENDPGM:
             ENDPGM
