      *****************************************************************
      *                                                               *
      *  Midas - IRS Validation Module                                *
      *                                                               *
      *  LUC120_002 - Midas IR: Validate Interest Payment frequency   *
      *                                                               *
      *  (C) Copyright Finastra Internatonal Limited 2019             *
      *                                                               *
      *  Last Amend No. LUC120  *CREATE    Date 13Feb19               *
      *                                                               *
      *****************************************************************
      *                                                               *
      *  LUC120 - Allow frequency 'W' (Weekly) or 'F' (Fortnightly).  *
      *                                                               *
      *---------------------------------------------------------------*
      *
     C                   END                                                                  LUC120
      *                                                                                       LUC120
